input {
  http_poller {
    urls => {
      cartas_magic => {
        method => get
        url => "http://192.199.1.57:8000/cards-data"
        headers => { Accept => "application/json" }
      }
    }
    request_timeout => 180
    schedule => { every => "2d" }
    codec => json
  }
}
