filter {
  # Solo procesa si existe el campo [message] y no es NilClass
  if [message] and [message] !~ /NilClass/ {
    
    # Divide el array en objetos individuales
    split { field => "[message]" }

    # Renombra el objeto resultante a "carta"
    mutate {
      rename => { "[message]" => "carta" }
    }

    mutate {
      copy => { "[carta][oracle_id]"          => "oracle_id" }
      copy => { "[carta][parent_id]"          => "parent_id" }
      copy => { "[carta][face_number]"        => "face_number" }
      copy => { "[carta][name]"               => "name" }
      copy => { "[carta][lang]"               => "lang" }
      copy => { "[carta][released_at]"        => "released_at" }
      copy => { "[carta][image_png]"          => "image_png" }
      copy => { "[carta][mana_cost]"          => "mana_cost" }
      copy => { "[carta][cmc]"                => "cmc" }
      copy => { "[carta][type_line]"          => "type_line" }
      copy => { "[carta][oracle_text]"        => "oracle_text" }
      copy => { "[carta][power]"              => "power" }
      copy => { "[carta][toughness]"          => "toughness" }
      copy => { "[carta][commander_legality]" => "commander_legality" }
      copy => { "[carta][game_changer]"       => "game_changer" }
      copy => { "[carta][set_name]"           => "set_name" }
      copy => { "[carta][rarity]"             => "rarity" }
      copy => { "[carta][artist]"             => "artist" }
      copy => { "[carta][full_art]"           => "full_art" }
      copy => { "[carta][booster]"            => "booster" }
      copy => { "[carta][ranking]"            => "ranking" }
      copy => { "[carta][price_usd]"          => "price_usd" }
      copy => { "[carta][price_usd_foil]"     => "price_usd_foil" }
      copy => { "[carta][price_usd_etched]"   => "price_usd_etched" }
      copy => { "[carta][cardmarket_url]"     => "cardmarket_url" }
      copy => { "[carta][embedding]"          => "embedding" }
    }

    # Elimina el objeto anidado para que no quede duplicado
    mutate {
      remove_field => ["carta"]
    }

    # Elimina los campos especiales de Logstash
    mutate {
      remove_field => ["@timestamp", "@version"]
    }
  }
}
