output {
  # Output normal hacia Elasticsearch
  elasticsearch {
    hosts => [
      "https://192.199.1.55:9200",
      "https://192.199.1.56:9200",
      "https://192.199.1.57:9200"
    ]
    index => "cartas_magic"
    document_id => "%{oracle_id}" # usamos el campo unico oracle_id como ID para indexar las cartas
    action => "update"
    doc_as_upsert => true         # si existe hace update, si no existe hace insert
    # Credenciales: usar el keystore de Logstash para inyectar la API key.
    # Ejecutar: bin/logstash-keystore add LOGSTASH_API_KEY
    # Formato del valor: "<API_KEY_ID>:<API_KEY_SECRET>"
    api_key => "${LOGSTASH_API_KEY}"
 
    #user => "elastic"
    #password => "${LOGSTASH_ES_PASSWORD}"
 
    ssl_certificate_authorities => ["/home/g1/elasticsearch-9.2.1/config/certs/http_ca.crt"]
    ssl_verification_mode => "full"  # asegura que se valide el certificado
  }
 
  # Output adicional para errores detectados
  if "grok_error_obtencion_cartas" in [tags] {
    file {
      path => "/home/g1/logstash-9.2.1/conf/pipeline_cartas/grok_error_obtencion_cartas-%{+YYYY-MM-dd}.log"
      codec => line { format => "Error: %{message}" }
    }
  }
 
  # Para depuración
  stdout { codec => rubydebug }
}
 
